version: '3.8'

services:
  # Service pour MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Service pour l'application Node.js
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: node-app
    depends_on:
      - mongo
    ports:
      - "5001:5001" # Le port de votre application
    volumes:
      - ./src:/usr/src/app/src # Synchronisation du dossier src
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongo-db:27017/${MONGO_INITDB_DATABASE}
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
